//
// Created by cyphics on 22/10/2020.
//

#ifndef TRANSVERSE_GUI_CONSTANTS_H
#define TRANSVERSE_GUI_CONSTANTS_H

#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 600
#define SCALE_FACTOR 1
#define PADDING 5 * SCALE_FACTOR
#define FONT_SIZE 30
#define MAX_UPGRADE_NAME_LENGTH 250 * SCALE_FACTOR
#define TEXT_RECT_HEIGHT 0 * SCALE_FACTOR

#endif //TRANSVERSE_GUI_CONSTANTS_H
